server:
  port: 9091
  servlet:
    context-path: /

spring:
  thymeleaf: # ThymeleafProperties
    prefix: classpath:/public/ # thymeleaf模板文件前缀，可以自定义文件夹如classpath:/templates/temp
    suffix: .html # thymeleaf模板文件后缀
    mode: HTML # 视图模板类型
    encoding: UTF-8 # 默认视图编码格式
    cache: true # 配置页面缓存，thymeleaf默认开启缓存，页面不能及时刷新，需要关闭
    servlet:
      content-type: text/html # 响应类型
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./system.db
  sql:
    init:
      platform: sqlite
      mode: always
      schema-locations:
        - classpath:db/init-schema.sql
      continue-on-error: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mapper/*.xml

# JWT配置
jwt:
  secret: cloudRenderServerJwtSecretKey2024ForAuthenticationAndAuthorization
  expiration: 86400000    # 24小时，单位毫秒
  refresh-expiration: 604800000  # 7天，单位毫秒

# 日志配置
logging:
  level:
    com.xudri.cloudrenderserver: DEBUG
    org.springframework.security: DEBUG

